# -*- coding: utf-8 -*-
"""sort_object.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iEoK5N4xWw7i-58pyamNUXj013bkacNa
"""

obj_data = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'dice': [155, 38], 'mouse': [200, 45], 'keyboard': [298, 65], 'fan': [300, 36]}

sorted_obj = sorted(obj_data.items(), key=lambda x: x[1][0])

for item in sorted_obj:
    print(item[0], item[1])